server:
  port: 8080
spring:
  application:
    name: zipkin
eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://172.17.0.2:8080/eureka/